# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "custom_strategy.rb"
class Crawl < Formula
  desc ""
  homepage "https://github.com/tresio/homebrew-tools"
  version "1.0.9"

  on_macos do
    on_intel do
      url "https://github.com/tresio/site-crawler/releases/download/v1.0.9/site-crawler_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "ff6daeff9ee91f3390356556fbd6f0d577b826b8f0a35c6c9924fe38375af7a8"

      def install
        bin.install "site-crawler"
      end
    end
    on_arm do
      url "https://github.com/tresio/site-crawler/releases/download/v1.0.9/site-crawler_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "fb12ca1f963c1f16decff5db2dc55695c7382ec592423e4aa53242551b002a48"

      def install
        bin.install "site-crawler"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tresio/site-crawler/releases/download/v1.0.9/site-crawler_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "1d7de62051f0b55283700f4f6dcb670f9ba97140474e4398d7afbe50cfb7b1e5"

        def install
          bin.install "site-crawler"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tresio/site-crawler/releases/download/v1.0.9/site-crawler_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "0dcce5299b6dba26dc8f35495211c063f24af30a8d2417a489bc6ff82fe6223d"

        def install
          bin.install "site-crawler"
        end
      end
    end
  end
end
