# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crawl < Formula
  desc ""
  homepage "https://github.com/tresio/homebrew-tools"
  version "1.0.7"

  on_macos do
    on_intel do
      url "https://github.com/tresio/site-crawler/releases/download/v1.0.7/site-crawler_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "7c2f1e3fdf0cd09da272f45c05865cddae124f5010f56d10b3d2247e7fc0c2c4"

      def install
        bin.install "site-crawler"
      end
    end
    on_arm do
      url "https://github.com/tresio/site-crawler/releases/download/v1.0.7/site-crawler_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "cffccddd155a64540426143a9db79feb5d185cb93c0cd8b0bf622fd7081d9503"

      def install
        bin.install "site-crawler"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tresio/site-crawler/releases/download/v1.0.7/site-crawler_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "3475f04238df3e7201b2ca0fb27689d70e3922374ee963252529548bbdfd0252"

        def install
          bin.install "site-crawler"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tresio/site-crawler/releases/download/v1.0.7/site-crawler_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "b6d5f75382045bb8278825ea347ebaa647353be63d58130808a257f07bbe6315"

        def install
          bin.install "site-crawler"
        end
      end
    end
  end
end
