# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crawl < Formula
  desc ""
  homepage "https://github.com/tresio/homebrew-tools"
  version "1.0.6"

  on_macos do
    on_intel do
      url "https://github.com/tresio/site-crawler/releases/download/v1.0.6/site-crawler_Darwin_x86_64.tar.gz"
      sha256 "2b752877680ec44560de9f1b4e41645aa36280b6ce4d32f8fc590ef4c7f2e9f7"

      def install
        bin.install "site-crawler"
      end
    end
    on_arm do
      url "https://github.com/tresio/site-crawler/releases/download/v1.0.6/site-crawler_Darwin_arm64.tar.gz"
      sha256 "32c326e42dfd59d1fd42f7a6534a36eb262b82aa8793f4c021a78e2bb43fbe11"

      def install
        bin.install "site-crawler"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tresio/site-crawler/releases/download/v1.0.6/site-crawler_Linux_x86_64.tar.gz"
        sha256 "89f82349c00b59bfb503858837bf1d4199417aebfbde01aae93f4fab41762e0c"

        def install
          bin.install "site-crawler"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tresio/site-crawler/releases/download/v1.0.6/site-crawler_Linux_arm64.tar.gz"
        sha256 "eb90aec3f7fcd7799085f1b51c1187fde8f561b132c25aaaf748b5f2a48cafb4"

        def install
          bin.install "site-crawler"
        end
      end
    end
  end
end
