# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "custom_strategy.rb"
class SiteCrawler < Formula
  desc ""
  homepage "https://github.com/tresio/homebrew-tools"
  version "1.0.10"

  on_macos do
    on_intel do
      url "https://github.com/tresio/site-crawler/releases/download/v1.0.10/site-crawler_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "f96fccc17c40cdcf66d76d828ec57da0f9944aefc7db09197a21e001eb831061"

      def install
        bin.install "site-crawler"
      end
    end
    on_arm do
      url "https://github.com/tresio/site-crawler/releases/download/v1.0.10/site-crawler_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "fbe190bc16fb30c0963f3b2969dfa7a31dab2704faf6701c8da0a7bd099d4df1"

      def install
        bin.install "site-crawler"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tresio/site-crawler/releases/download/v1.0.10/site-crawler_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "cc519ebb89c05c38311f33bb92d1e56e6ce2153fe5e6ab43da18bdb8d40e1303"

        def install
          bin.install "site-crawler"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tresio/site-crawler/releases/download/v1.0.10/site-crawler_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "391dbb65c396e67b8e229eb33cafb97c84e93284f6e364b2656fe706fa637b51"

        def install
          bin.install "site-crawler"
        end
      end
    end
  end
end
